spring:
  application:
    name: @project.name@
    version: @project.version@

management:
  jmx:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
