name: Build & Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  native-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Generate native image
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          
          ./mvnw -B spring-boot:build-image \
              -Pnative \
              -Dspring-boot.build-image.imageName=ghcr.io/${{ github.actor }}/${{github.event.repository.name}}:$(date +%d%m%Y%H%M)
          
          docker images -a
      - name: Login to GitHub Container Registry
        if: matrix.os == 'ubuntu-latest'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker push
        run: docker push -a ghcr.io/${{ github.actor }}/${{github.event.repository.name}}
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '21'
        components: 'native-image'
        cache: 'maven'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Publish maven artifact to GitHub Packages
      run: |
        #./mvnw -B native:compile
        ./mvnw -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Github Release
      run: gh release create v1.0.0 ./target/*.jar
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}