name: Maven Build & Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github

    - name: Publish maven artifact to GitHub Packages
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Github Release
      run: gh release create v1.0.0 ./target/*.jar
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}