name: Build
on:
  push:
    branches:
      - main
jobs:
  compile-test-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: push package
        run: ./mvnw -B -s settings.xml clean deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}