name: Build
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  upload-JAR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: push JAR
        run: ./mvnw -B -s settings.xml clean deploy
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload-IMAGE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: native image build
        run: |
          VERSION=$(date "+%Y%m%d%H%M%S")
          ./mvnw -B \
              -s settings.xml \
              spring-boot:build-image \
              -Pnative \
              -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:$VERSION
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker images -a
          docker push ghcr.io/${{ github.repository }}